
// Pili, Camarines Sur Barangays
export const PILI_BARANGAYS = [
  "Anayan",
  "Bagong Sirang",
  "Binanwaanan",
  "Binobong",
  "Cadlan",
  "Caroyroyan",
  "Curry",
  "Del Rosario",
  "Himaao",
  "La Purisima",
  "New San Roque",
  "Old San Roque",
  "Palestina",
  "Pawili",
  "Sagrada",
  "Sagurong",
  "San Agustin",
  "San Antonio",
  "San Isidro",
  "San Jose",
  "San Juan",
  "San Vicente",
  "Santiago",
  "Santo Niño",
  "Tagbong",
  "Tinangis"
] as const;

// Standardized Job Categories (used across all components)
export const JOB_CATEGORIES = [
  "Education",
  "Healthcare",
  "Retail",
  "Food Service",
  "Transportation",
  "Construction",
  "Agriculture",
  "Government",
  "Technology",
  "Manufacturing",
  "Tourism",
  "Banking & Finance",
  "Real Estate",
  "Security",
  "Customer Service",
  "Sales & Marketing",
  "Administrative",
  "Engineering",
  "Legal",
  "Beauty & Wellness",
  "Entertainment",
  "Non-Profit",
  "Consulting",
  "Media & Communications",
  "Other"
] as const;
